### ISSUE TITLE
Docker image expired

### ISSUE THREAD

**Issue by leso-kn** [Commit451/android-sdk-installer#1]
First of all, thanks for this great software bundle!
Been using it for several years now to build my Android apps via CI.

Today I noticed, that the docker image ([commit451/android-sdk-installer](https://hub.docker.com/r/commit451/android-sdk-installer/)) has expired and is no longer available for pulling. This is probably related to [changes to the docker policy](https://www.docker.com/blog/scaling-dockers-business-to-serve-millions-more-developers-storage/)* that were applied last year.

Pushing the image again should make it available again for the next 6 months.

Ideally, the Dockerfile could be uploaded to the repository to make it easy to re-create the image in the future.

Thanks and keep up the good work!

> \* CTRL+F search the blog post for "6 months"

**Comment by Jawnnypoo** [comment]
Hey there! We actually removed the package in favor of https://github.com/Commit451/docker-android which is hosted on Docker Hub as well:
https://hub.docker.com/repository/docker/commit451/docker-android

Maybe you can switch to using this one instead? The main reason was that we needed to be building with Java 11 instead of Java 8 for Compose and wanted to make the docker image more "modern" at the same time. Let me know what you think!

**Comment by leso-kn** [comment]
oh, I didn't know. Thanks, I'll check it out!
Maybe the docker section of the readme could be updated with this info.

I'll re-open this issue if I notice anything major, other than that, thanks for the quick reply!
